DROP USER THIHK;

CREATE USER THIHK PROFILE DEFAULT 

IDENTIFIED BY THIHK DEFAULT TABLESPACE SYSTEM

TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;

GRANT SELECT ANY DICTIONARY TO THIHK;
/
GRANT UNLIMITED TABLESPACE TO THIHK;
/
GRANT CONNECT TO THIHK;
/
GRANT RESOURCE TO THIHK;